### PR TITLE
Don't require build_number to be numeric

### LINKED ISSUE #10: CORDOVA_BUILD_NUMBER environment variable doesn't work
If I run my lane that uses the `cordova` action with the `CORDOVA_BUILD_NUMBER` environment variable set, I get an error:

```
'build_number' value must be a Numeric! Found String instead.
```

This is the same error I get when I pass `build_number` into the `cordova` action from the `Fastfile`, e.g.:

```ruby
cordova(
    platform: "android",
    build_number: 7,
)
```

works, but this:

```ruby
cordova(
    platform: "android",
    build_number: "7",
)
```

gives me the same error message as when I use `CORDOVA_BUILD_NUMBER`.

As far as I know, they're no way to really pass a number via environment variables, they're always strings and you have to parse the number out if you want that. Therefore, one possible solution would be to parse the environment variable to a number before using it, and only fail if it's not a valid integer.

That said, I'm not sure restricting `build_number` to being a number is the right thing to do. On iOS, `build_number` corresponds to `CFBundleVersion`, which can be non-numeric values such as "1.2" or "1.2.3". I'd suggest instead allowing `build_number` to be either a number or a string, and simply pass the string directly through to the Cordova CLI.

### PR DESCRIPTION
**Pull request by excaliburHisSheath**
Fixes #10

This is a potential fix for the issue described in #10. This completely removes the restriction that `build_number` be a numeric value, which allows fastlane-plugin-cordova to better support the full range of allowed values for CFBundleVersion on iOS. If that's not desirable, there might be another way to just allow numeric values in environment variables.

I haven't added any test cases because it doesn't look like this project has any, but I manually tested and verified that #10 is resolved and that this isn't a breaking change for existing projects, i.e.:

```ruby
cordova(
    platform: "android",
    build_number: 7,
)
```

```ruby
cordova(
    platform: "android",
    build_number: "7",
)
```

```
CORDOVA_BUILD_NUMBER=7 bundle exec fastlane cordova ...
```

all work as intended, you can still pass `build_number` in as either a number or a string.

### CODE REVIEW

File: lib/fastlane/plugin/cordova/actions/cordova_action.rb [hunk 1]
```diff
@@ -192,9 +192,8 @@ def self.available_options
             key: :build_number,
             env_name: "CORDOVA_BUILD_NUMBER",
             description: "Build Number for iOS and Android Keystore alias",
-            default_value: 0,
+            optional: true,
             is_string: false,
```
Comment (excaliburHisSheath) [inline lib/fastlane/plugin/cordova/actions/cordova_action.rb]: I saw that `is_string` is deprecated, but it seems like the other config items are still using it and I wanted to keep consistent. I can switch to using `type` instead, if you're cool with `build_number` being declared slightly differently from the other config items.

As for choosing a specific type, I don't want it to just be `String`, it should accept a `String` or a `Numeric` (well, really an `Integer`). Just accepting a string would be fine, but it would be a breaking change because previous versions did accept numbers for `build_number`. I left `is_string` false, because that allows it to accept both strings and numbers. I don't know what the equivalent would be if I used `type` instead (maybe just not specifying `type` would be enough).

Comment (stalniy) [inline lib/fastlane/plugin/cordova/actions/cordova_action.rb]: Fair enough

**Comment by excaliburHisSheath** [comment]
I've fixed the outstanding build conflict, so this should now be able to be merged.

**Comment by Almouro** [comment]
Awesome, thanks! Merging and publishing ASAP :)

**Comment by Almouro** [comment]
Done! Thanks @excaliburHisSheath and @stalniy !
By the way, do you guys know a tool to automatically publish gem releases when merging?
In JS, we use [Semantic Release](https://github.com/semantic-release/semantic-release) which is awesome for that.
